apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    io.kompose.service: golang
    heritage: {{ $.Release.Service | quote }}
    release: {{ $.Release.Name | quote }}
    chart: {{ template "name.chart" $ }}
  name: golang-{{ template "name.fullname" . }}
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: golang
  strategy: {}
  template:
    metadata:
      labels:
        io.kompose.service: golang
    spec:
      containers:
        - image: golang
          name: golang
          ports:
            - containerPort: {{ .Values.app.probe.port }}
            - containerPort: {{ .Values.app.published_port }}
          # define a liveness probe that checks every 5 seconds, starting after 5 seconds
          livenessProbe:
            httpGet:
              path: /live
              port: {{ .Values.app.probe.port }}
            initialDelaySeconds: 5
            periodSeconds: 5

          # define a readiness probe that checks every 5 seconds
          readinessProbe:
            httpGet:
              path: /ready
              port: {{ .Values.app.probe.port }}
            periodSeconds: 5
      restartPolicy: Always
status: {}

apiVersion: v1
kind: Service
metadata:
  labels:
    io.kompose.service: golang
    heritage: {{ $.Release.Service | quote }}
    release: {{ $.Release.Name | quote }}
    chart: {{ template "name.chart" $ }}
  name: golang
spec:
  ports:
    - name: "{{ .Values.app.probe.port }}"
      port: {{ .Values.app.probe.port }}
      targetPort: {{ .Values.app.probe.port }}
    - name: "{{ .Values.app.published_port }}"
      port: {{ .Values.app.published_port }}
      targetPort: {{ .Values.app.target_port }}
  selector:
    io.kompose.service: golang
  type: LoadBalancer

