apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- namespace.yaml
- golang-deployment.yaml
- golang-service.yaml
- grafana-deployment.yaml
- grafana-service.yaml
- grafana-storage-persistentvolumeclaim.yaml
- prometheus-claim0-persistentvolumeclaim.yaml
- prometheus-data-persistentvolumeclaim.yaml
- prometheus-deployment.yaml
- prometheus-service.yaml
- ingress.yaml
namespace: development
